version: "3.8"
services:
  prolog:
    image: swipl:latest
    container_name: prolog-container
    build:
      context: .
    volumes:
      - .:/app
      - /var/run/postgresql:/var/run/postgresql
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: prolog_user
      POSTGRES_PASSWORD: prolog_pass
      POSTGRES_DB: facts_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql
    entrypoint: ["docker-entrypoint.sh", "postgres"]

volumes:
  db-data:
